### PR TITLE
applied fix for the post/02

### PR DESCRIPTION
**Pull request by piyoki**
### Summary

Apply fixes for post/02 -- How to `cloudflared`

### Details

- [x] fixed a few grammas

### Checks

- [x] Already tested changes in `staging` environment

### Notes

We may further discuss in detail if the applied changes are good enough to proceed to `production`.

### CODE REVIEW

**Comment by kunish** [comment]
LGTM.

Thanks mate. Now it reads flawlessly.

**Comment by piyoki** [comment]
> LGTM.
> 
> Thanks mate. Now it reads flawlessly.

Good to know. Feel free to merge anytime xD

**Review by kunish — APPROVED** [review]
Really precise and professional fixes. I really appreciate that.

**Pull request merged**
